package ch.cern.todo.exceptions;

public class AlreadyExistsException extends Exception{}
